version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./nginx-container/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  test:
    environment:
      - DB_HOST=mongodb://mongo/telepath-api
    container_name: test
    build:
      context: ./
      dockerfile: Dockerfile-Test
    depends_on:
      - mongo
    links: 
      - mongo

  app:
    environment:
      - DB_HOST=mongodb://mongo/telepath-api
    container_name: app
    restart: always
    build: .
    depends_on:
      - test
    links:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo