version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./nginx-container/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    environment:
      - DB_HOST=mongodb://mongo/telepath-api
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"